apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-spring-boot-BRANCH_NAME
    date: APPLY_TIMESTAMP
  name: hello-spring-boot-BRANCH_NAME
  namespace: demo-pic
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: hello-spring-boot-BRANCH_NAME
  template:
    metadata:
      labels:
        app: hello-spring-boot-BRANCH_NAME
    spec:
      containers:
        - name: hello-spring-boot
          image: registry.demo-pic.techlead-top.ovh/hello-spring-boot:BRANCH_NAME
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 8080
      imagePullSecrets:
        - name: docker-registry-config
---
apiVersion: v1
kind: Service
metadata:
  name: hello-spring-boot-BRANCH_NAME
  namespace: demo-pic
  labels:
    date: APPLY_TIMESTAMP
spec:
  selector:
    app: hello-spring-boot-BRANCH_NAME
  ports:
    - name: web
      port: 8080
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-spring-boot-BRANCH_NAME
  namespace: demo-pic
  labels:
    date: APPLY_TIMESTAMP
spec:
  rules:
    - host: hello-spring-boot.BRANCH_NAME.demo-pic.techlead-top.ovh
      http:
        paths:
          - path: /
            backend:
              serviceName: hello-spring-boot-BRANCH_NAME
              servicePort: web